### PR TITLE
More derive implementations, fixed spelling mistakes

### PR DESCRIPTION
**Pull request by eliasfloreteng**
I was doing some unit test and needed to check equality of Message type with `assert_eq!` but found out `PartialEq` wasn't implemented. While creating this PR, to add `PartialEq` (and a few more derives) I also found some spelling mistakes that I fixed (it happens to all of us).

### CODE REVIEW

**Comment by eminence** [comment]
Hi @elias123tre 

I was doing some work last night on updating the library, including some new testing/fuzzing, so I also ran into the `PartialEq` problem.  I've just pushed my work, hopefully it didn't clobber too much of what you're working on.

Can you take a look and update the PR?   Thanks.

**Comment by eliasfloreteng** [comment]
I've made a merge commit now. You can look through it to see if everything looks good as I'm not that familiar with the `arbitrary` crate.

**Comment by eminence** [comment]
LGTM, thanks

**Comment by eminence** [comment]
Published as `v0.3.1`

**Pull request merged**
