### PR TITLE
Add tests of captured messages to ensure they are correct

### PR DESCRIPTION
**Pull request by Firstyear**
This extends my previous commit with tests to ensure that everything works as intended. These were packet captured between my iOS device and a LIFX Z strip, and I used them to check that everything was happy.

### CODE REVIEW

**Comment by eliasfloreteng** [comment]
It's great to test with example packets but shouldn't the tests also assert that `msg` is the right type of message and has the right values to assure it gets parsed correctly. Instead of just printing it?

**Comment by Firstyear** [comment]
Opps good point! This will teach me for half-assing commits while busy ^^; :)

**Comment by Firstyear** [comment]
Fixed, sorry about that!

**Comment by eminence** [comment]
Looks good, thanks!

**Comment by Firstyear** [comment]
Thank you @eminence !

**Pull request merged**
